[package]
name = "rust_openssl_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
jni = "0.20.0"
openssl-sys = "0.9"
openssl = "0.10"

[lib]
crate-type = ["lib"]
name = "rust_openssl_lib"
path = "src/lib.rs"
